# ./Dockerfile

FROM golang:alpine AS builder

# Move to working directory (/app).
WORKDIR /app

# Copy and download dependency using go mod.
COPY ../go.mod ../go.sum ./
RUN go mod download

# Copy the code into the container.
COPY . .

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
RUN go build -ldflags="-s -w" -o refactory-auth .

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/

#COPY --from=builder ["/app/online-library-api", "/app/.env", "/"]
COPY --from=builder /app/refactory-auth .
COPY --from=builder /app/.env .

# Export necessary port
EXPOSE 3000

# Command to run when starting the container.
CMD ["./refactory-auth"]
